/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ZamaConfig } from "./ZamaConfig";
export type { ZamaEthereumConfig } from "./ZamaEthereumConfig";
