/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UniversalFHEAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "businessData"
      | "businessIds"
      | "confidentialProtocolId"
      | "createBusinessData"
      | "getAllBusinessIds"
      | "getBusinessData"
      | "getEncryptedValue"
      | "isAvailable"
      | "verifyDecryption"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BusinessDataCreated"
      | "DecryptionVerified"
      | "PublicDecryptionVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "businessData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "businessIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createBusinessData",
    values: [
      string,
      string,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllBusinessIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBusinessData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedValue",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isAvailable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDecryption",
    values: [string, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "businessData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "businessIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBusinessData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllBusinessIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBusinessData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDecryption",
    data: BytesLike
  ): Result;
}

export namespace BusinessDataCreatedEvent {
  export type InputTuple = [businessId: string, creator: AddressLike];
  export type OutputTuple = [businessId: string, creator: string];
  export interface OutputObject {
    businessId: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionVerifiedEvent {
  export type InputTuple = [businessId: string, decryptedValue: BigNumberish];
  export type OutputTuple = [businessId: string, decryptedValue: bigint];
  export interface OutputObject {
    businessId: string;
    decryptedValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniversalFHEAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): UniversalFHEAdapter;
  waitForDeployment(): Promise<this>;

  interface: UniversalFHEAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  businessData: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        name: string;
        encryptedValue: string;
        publicValue1: bigint;
        publicValue2: bigint;
        description: string;
        creator: string;
        timestamp: bigint;
        decryptedValue: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  businessIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createBusinessData: TypedContractMethod<
    [
      businessId: string,
      name: string,
      encryptedValue: BytesLike,
      inputProof: BytesLike,
      publicValue1: BigNumberish,
      publicValue2: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  getAllBusinessIds: TypedContractMethod<[], [string[]], "view">;

  getBusinessData: TypedContractMethod<
    [businessId: string],
    [
      [string, bigint, bigint, string, string, bigint, boolean, bigint] & {
        name: string;
        publicValue1: bigint;
        publicValue2: bigint;
        description: string;
        creator: string;
        timestamp: bigint;
        isVerified: boolean;
        decryptedValue: bigint;
      }
    ],
    "view"
  >;

  getEncryptedValue: TypedContractMethod<
    [businessId: string],
    [string],
    "view"
  >;

  isAvailable: TypedContractMethod<[], [boolean], "view">;

  verifyDecryption: TypedContractMethod<
    [
      businessId: string,
      abiEncodedClearValue: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "businessData"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        name: string;
        encryptedValue: string;
        publicValue1: bigint;
        publicValue2: bigint;
        description: string;
        creator: string;
        timestamp: bigint;
        decryptedValue: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "businessIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createBusinessData"
  ): TypedContractMethod<
    [
      businessId: string,
      name: string,
      encryptedValue: BytesLike,
      inputProof: BytesLike,
      publicValue1: BigNumberish,
      publicValue2: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllBusinessIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBusinessData"
  ): TypedContractMethod<
    [businessId: string],
    [
      [string, bigint, bigint, string, string, bigint, boolean, bigint] & {
        name: string;
        publicValue1: bigint;
        publicValue2: bigint;
        description: string;
        creator: string;
        timestamp: bigint;
        isVerified: boolean;
        decryptedValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedValue"
  ): TypedContractMethod<[businessId: string], [string], "view">;
  getFunction(
    nameOrSignature: "isAvailable"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyDecryption"
  ): TypedContractMethod<
    [
      businessId: string,
      abiEncodedClearValue: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BusinessDataCreated"
  ): TypedContractEvent<
    BusinessDataCreatedEvent.InputTuple,
    BusinessDataCreatedEvent.OutputTuple,
    BusinessDataCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionVerified"
  ): TypedContractEvent<
    DecryptionVerifiedEvent.InputTuple,
    DecryptionVerifiedEvent.OutputTuple,
    DecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;

  filters: {
    "BusinessDataCreated(string,address)": TypedContractEvent<
      BusinessDataCreatedEvent.InputTuple,
      BusinessDataCreatedEvent.OutputTuple,
      BusinessDataCreatedEvent.OutputObject
    >;
    BusinessDataCreated: TypedContractEvent<
      BusinessDataCreatedEvent.InputTuple,
      BusinessDataCreatedEvent.OutputTuple,
      BusinessDataCreatedEvent.OutputObject
    >;

    "DecryptionVerified(string,uint32)": TypedContractEvent<
      DecryptionVerifiedEvent.InputTuple,
      DecryptionVerifiedEvent.OutputTuple,
      DecryptionVerifiedEvent.OutputObject
    >;
    DecryptionVerified: TypedContractEvent<
      DecryptionVerifiedEvent.InputTuple,
      DecryptionVerifiedEvent.OutputTuple,
      DecryptionVerifiedEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
  };
}

