/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ZamaConfig__factory } from "./ZamaConfig__factory";
export { ZamaEthereumConfig__factory } from "./ZamaEthereumConfig__factory";
